### ISSUE TITLE
.clap release

### ISSUE THREAD

**Issue by RustoMCSpit** [stfufane/midi_transpose_rs#1]
id like to add this to my list https://github.com/RustoMCSpit/awesome-linux-clap-list

**Comment by stfufane** [comment]
Hey there, thanks for the message. I don't think it's ready to be shared in that kind of list yet, it's not finished and barely useable as it is, it needs a bit of development that I'll do in a near future, then I'll notify you :)

**Comment by RustoMCSpit** [comment]
half the plugins in my list do not even open or work. trust me, the bar is in fucking hell. id love to just add it and have it eventually be fixed then forget about this.

**Comment by RustoMCSpit** [comment]
as long as you commit to having a .clap soon i'll add it

**Comment by stfufane** [comment]
Well it builds a .clap and .vst3 plugin so I guess it meets the criteria, you can add it if you feel like it. I need to setup a github pipeline to build the binary but it's a bit early in development for this :)

**Comment by RustoMCSpit** [comment]
alright well if youre going to add it it's going in the list, thanks!
